apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client
  name: client
spec:
  containers:
  - command:
      - sh
      - -c
      - "
        \  while : ; do\n
        \        curl http://[$SERVER_IP]:80 ; sleep 60 \n
        \  done"
    image: quay.io/openshifttest/hello-openshift:multiarch
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        privileged: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    name: client
    resources: {}
status: {}
